import 'package:flutter/material.dart';
List<String> listImageLottey=[
  'assets/image/lottery_0.png',
  'assets/image/lottery_1.png',
  'assets/image/lottery_2.png',
  'assets/image/lottery_3.png',
  'assets/image/lottery_4.png',
  'assets/image/lottery_5.png',
  'assets/image/lottery_6.png',
  'assets/image/lottery_7.png',
  'assets/image/lottery_8.png',
  'assets/image/lottery_9.png',

  'assets/image/lottery_0.png',
  'assets/image/lottery_1.png',
  'assets/image/lottery_2.png',
  'assets/image/lottery_3.png',
  'assets/image/lottery_4.png',
  'assets/image/lottery_5.png',
  'assets/image/lottery_6.png',
  'assets/image/lottery_7.png',
  'assets/image/lottery_8.png',
  'assets/image/lottery_9.png',

  'assets/image/lottery_0.png',
  'assets/image/lottery_1.png',
  'assets/image/lottery_2.png',
  'assets/image/lottery_3.png',
  'assets/image/lottery_4.png',
  'assets/image/lottery_5.png',
  'assets/image/lottery_6.png',
  'assets/image/lottery_7.png',
  'assets/image/lottery_8.png',
  'assets/image/lottery_9.png',
];

List<Color> listColor =[ // 30 color
    Colors.red,
    Colors.blue,
    Colors.purpleAccent,
    Colors.green,
    Colors.deepOrange,
    Colors.pink,
    Colors.brown,
    Colors.deepPurple,
    Colors.purple,
    Colors.blueAccent,
    Colors.blueGrey,
    Colors.redAccent,
    Colors.lightBlue,
    Colors.grey,
    Colors.greenAccent,
    Colors.deepOrangeAccent,
    Colors.pinkAccent,
    Colors.white,
    Colors.deepPurpleAccent,
    Colors.deepPurpleAccent,

    // Colors.red,
    Colors.blue,
    Colors.purpleAccent,
    Colors.green,
    Colors.deepOrange,
    Colors.pink,
    Colors.brown,
    Colors.deepPurple,
    Colors.purple,
    Colors.blueAccent,
    Colors.blueGrey,
  ];